spring:
  data:
    mongodb:
      uri:

  rabbitmq:
    host: localhost
    port: 5672
    username:
    password:

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking